#!/bin/bash
echo "=== Testing Complete Casino War Part 6 ==="
echo ""
echo "This version includes all fixes:"
echo "✅ War resolution - dealer card flips properly"
echo "✅ Clear card display - Text2d with rank/suit"
echo "✅ Chip reset on game over"
echo "✅ Consistent button hover effects"
echo "✅ Clean code - removed unused events"
echo ""
echo "Test Checklist:"
echo "1. Main Menu - Click PLAY"
echo "2. Place bet with chip buttons"
echo "3. Click ENGAGE to deal"
echo "4. Watch cards - should see clear rank/suit (e.g. A♠, K♥)"
echo "5. On tie - choose GO TO WAR"
echo "6. War cards should deal and dealer card should flip"
echo "7. See war result"
echo "8. Click CONTINUE for next round"
echo "9. Lose all chips -> RESTART -> chips reset to 1000"
echo ""
echo "Starting game..."
cargo run